## static_countries
UPDATE static_countries SET cn_short_nl='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_nl='Verenigde Arabische Emiraten' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_nl='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_nl='Antigua en Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_nl='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_nl='Albanië' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_nl='Armenië' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_nl='Nederlandse Antillen' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_nl='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_nl='Antarctica' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_nl='Argentinië' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_nl='Amerikaans-Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_nl='Oostenrijk' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_nl='Australië' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_nl='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_nl='Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_nl='Azerbeidzjan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_nl='Bosnië en Herzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_nl='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_nl='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_nl='België' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_nl='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_nl='Bulgarije' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_nl='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_nl='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_nl='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_nl='Saint-Barthélemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_nl='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_nl='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_nl='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_nl='Brazilië' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_nl='Bahama\'s' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_nl='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_nl='Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_nl='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_nl='Wit-Rusland' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_nl='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_nl='Canada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_nl='Cocoseilanden' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_nl='Congo-Kinshasa' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_nl='Centraal-Afrikaanse Republiek' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_nl='Congo-Brazzaville' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_nl='Zwitserland' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_nl='Ivoorkust' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_nl='Cookeilanden' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_nl='Chili' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_nl='Kameroen' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_nl='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_nl='Colombia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_nl='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_nl='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_nl='Kaapverdië' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_nl='Christmaseiland' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_nl='Cyprus' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_nl='Tsjechië' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_nl='Duitsland' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_nl='Djibouti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_nl='Denemarken' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_nl='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_nl='Dominicaanse Republiek' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_nl='Algerije' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_nl='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_nl='Estland' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_nl='Egypte' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_nl='Westelijke Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_nl='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_nl='Spanje' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_nl='Ethiopië' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_nl='Finland' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_nl='Fiji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_nl='Falklandeilanden' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_nl='Micronesia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_nl='Faeröer' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_nl='Frankrijk' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_nl='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_nl='Verenigd Koninkrijk' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_nl='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_nl='Georgië' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_nl='Frans-Guyana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_nl='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_nl='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_nl='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_nl='Groenland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_nl='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_nl='Guinee' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_nl='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_nl='Equatoriaal-Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_nl='Griekenland' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_nl='Zuid-Georgië en de Zuidelijke Sandwicheilanden' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_nl='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_nl='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_nl='Guinee-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_nl='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_nl='Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_nl='Heard en McDonaldeilanden' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_nl='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_nl='Kroatië' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_nl='Haïti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_nl='Hongarije' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_nl='Indonesië' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_nl='Ierland' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_nl='Israël' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_nl='Isle of Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_nl='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_nl='Brits Territorium in de Indische Oceaan' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_nl='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_nl='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_nl='IJsland' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_nl='Italië' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_nl='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_nl='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_nl='Jordanië' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_nl='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_nl='Kenia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_nl='Kirgizië' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_nl='Cambodja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_nl='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_nl='Comoren' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_nl='Saint Kitts en Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_nl='Noord-Korea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_nl='Zuid-Korea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_nl='Koeweit' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_nl='Kaaimaneilanden' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_nl='Kazachstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_nl='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_nl='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_nl='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_nl='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_nl='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_nl='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_nl='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_nl='Litouwen' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_nl='Luxemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_nl='Letland' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_nl='Libië' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_nl='Marokko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_nl='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_nl='Moldavië' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_nl='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_nl='Sint Maarten' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_nl='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_nl='Marshalleilanden' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_nl='Macedonië' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_nl='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_nl='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_nl='Mongolië' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_nl='Macau' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_nl='Noordelijke Marianen' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_nl='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_nl='Mauritanië' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_nl='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_nl='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_nl='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_nl='Maldiven' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_nl='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_nl='Mexico' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_nl='Maleisië' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_nl='Mozambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_nl='Namibië' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_nl='Nieuw-Caledonië' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_nl='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_nl='Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_nl='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_nl='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_nl='Nederland' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_nl='Noorwegen' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_nl='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_nl='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_nl='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_nl='Nieuw-Zeeland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_nl='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_nl='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_nl='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_nl='Frans-Polynesië' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_nl='Papoea-Nieuw-Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_nl='Filipijnen' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_nl='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_nl='Polen' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_nl='Saint-Pierre en Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_nl='Pitcairneilanden' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_nl='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_nl='Palestijnse Autoriteit' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_nl='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_nl='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_nl='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_nl='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_nl='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_nl='Roemenië' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_nl='Servië' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_nl='Rusland' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_nl='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_nl='Saoedi-Arabië' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_nl='Salomonseilanden' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_nl='Seychellen' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_nl='Soedan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_nl='Zweden' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_nl='Singapore' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_nl='Sint-Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_nl='Slovenië' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_nl='Spitsbergen en Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_nl='Slowakije' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_nl='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_nl='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_nl='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_nl='Somalië' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_nl='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_nl='Sao Tomé en Principe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_nl='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_nl='Syrië' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_nl='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_nl='Turks- en Caicoseilanden' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_nl='Tsjaad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_nl='Franse Zuidelijke en Antarctische Gebieden' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_nl='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_nl='Thailand' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_nl='Tadzjikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_nl='Tokelau-eilanden' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_nl='Oost-Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_nl='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_nl='Tunesië' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_nl='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_nl='Turkije' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_nl='Trinidad en Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_nl='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_nl='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_nl='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_nl='Oekraïne' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_nl='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_nl='Kleine Pacifische eilanden van de Verenigde Staten' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_nl='Verenigde Staten' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_nl='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_nl='Oezbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_nl='Vaticaanstad' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_nl='Saint Vincent en de Grenadines' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_nl='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_nl='Britse Maagdeneilanden' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_nl='Amerikaanse Maagdeneilanden' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_nl='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_nl='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_nl='Wallis en Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_nl='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_nl='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_nl='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_nl='Zuid-Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_nl='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_nl='Zimbabwe' WHERE cn_iso_2='ZW';
## static_country_zones
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='AK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='AZ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='DE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='DC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='FL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='GA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='GU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='HI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='ID';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='IL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='IN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='IA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='KS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='KY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='LA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NJ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='NC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='ND';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='OH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='OK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='SD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='TX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='UT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='WV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='US' AND zn_code='WY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='AB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='MB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='NF';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='NB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='NS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='ON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='QC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='SK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CA' AND zn_code='YT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='NDS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='BAW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='BAY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='BER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='BRG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='BRE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='HAM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='HES';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='MEC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='NRW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='RHE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='SAR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='SAS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='SAC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='SCN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='DE' AND zn_code='THE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='OO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='SB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='KN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='ST';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AT' AND zn_code='VB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='CH' AND zn_code='ZH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Alava';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Malaga';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Segovia';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Granada';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Jaen';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Sevilla';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Barcelona';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Valencia';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Alicante';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Almeria';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Asturias';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Avila';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Badajoz';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Burgos';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Caceres';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Cadiz';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Cantabria';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Castellon';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Ceuta';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Ciudad Real';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Cordoba';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Cuenca';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Girona';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Las Palmas';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Guadalajara';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Guipuzcoa';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Huelva';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Huesca';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='A Coruña';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='La Rioja';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Leon';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Lugo';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Lleida';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Madrid';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Baleares';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Murcia';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Navarra';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Ourense';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Palencia';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Pontevedra';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Salamanca';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Soria';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Tarragona';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Tenerife';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Teruel';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Toledo';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Valladolid';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Vizcaya';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Zamora';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Zaragoza';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='ES' AND zn_code='Melilla';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='AGS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='BCS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='CAM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='CHIS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='CHIH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='COAH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='COL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='DIF';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='DGO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='GTO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='GRO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='HGO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='JAL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='MEX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='MICH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='MOR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='NAY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='NL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='OAX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='PUE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='QRO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='QROO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='SLP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='SIN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='SON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='TAB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='TAMPS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='TLAX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='VER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='YUC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='MX' AND zn_code='ZAC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='ACT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='NSW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='QLD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='TAS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='VIC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='AU' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AQ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='AV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='BZ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='CZ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='EN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='FE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='FG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='FI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='FO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='IM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='IS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='KR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='LC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='LE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='LI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='LO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='LT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='MC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='NA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='PZ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='SV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='TV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='UD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IT' AND zn_code='VV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='ALD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='ARM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='ATM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BDS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BFD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BIR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BLG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BRI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BRK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BRS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='BUX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CAP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CAS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CBA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CBE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CHI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CHS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CLD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CNL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CTR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='CVE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DEN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DFD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DGL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DHM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DOR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DVN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DWN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='DYS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='ESX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='FER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='FFE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='FLI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='FMH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GDD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GLO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GLR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GNM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GNS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GNW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GRN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GUR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='GWT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='HBS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='HFD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='HLD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='HPH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='HWR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='IOM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='IOW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='ISL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='JER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='KNT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LCN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LDN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LDR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LEC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LNH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LTE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LTM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='LTW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='MCH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='MER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='MSY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NET';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NEW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NHM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NLD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NOR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NOT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='NWH';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='OFE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='ORK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='PEM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='PWS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SCD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SFD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SFK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SLD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SOM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SPE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SRK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SRY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SWA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SXE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='SXW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='TAF';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='TOR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='TWR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='TYR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='TYS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='VAL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='WIL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='WKS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='WLT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='WMD';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='WRE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='YSN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='YSS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='GB' AND zn_code='YSW';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='CAV';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='CLA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='COR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='DON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='DUB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='GAL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='KER';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='KIL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='KLK';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='LAO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='LEI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='LIM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='LOU';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='MAY';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='MEA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='OFF';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='ROS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='SLI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='TIP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='WAT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='WES';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='WEX';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='IE' AND zn_code='WIC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='AC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='AM';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='DF';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='ES';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='MG';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='PB';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='RJ';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='RR';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='RS';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='SE';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_nl='' WHERE zn_country_iso_2='BR' AND zn_code='TO';
## static_currencies
UPDATE static_currencies SET cu_name_nl='VAE-Dirham',cu_sub_name_nl='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_nl='Afghani',cu_sub_name_nl='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_nl='Albanese lek',cu_sub_name_nl='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_nl='Armeense dram',cu_sub_name_nl='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_nl='Antilliaanse gulden',cu_sub_name_nl='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_nl='Angolese kwanza',cu_sub_name_nl='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_nl='Argentijnse peso',cu_sub_name_nl='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_nl='Australische dollar',cu_sub_name_nl='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_nl='Arubaanse gulden',cu_sub_name_nl='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_nl='Azerbeidzjaanse manat',cu_sub_name_nl='' WHERE cu_iso_3='AZM';
UPDATE static_currencies SET cu_name_nl='Bosnische mark',cu_sub_name_nl='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_nl='Barbadiaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_nl='Bengalese taka',cu_sub_name_nl='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_nl='Nieuwe Bulgaarse lev',cu_sub_name_nl='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_nl='Bahreinse dinar',cu_sub_name_nl='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_nl='Burundese frank',cu_sub_name_nl='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_nl='Bermuda-dollar',cu_sub_name_nl='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_nl='Bruneise dollar',cu_sub_name_nl='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_nl='Boliviaanse boliviano',cu_sub_name_nl='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_nl='Braziliaanse real',cu_sub_name_nl='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_nl='Bahamaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_nl='Bhutaanse ngultrum',cu_sub_name_nl='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_nl='Botswaanse pula',cu_sub_name_nl='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_nl='Wit-Russische roebel',cu_sub_name_nl='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_nl='Belizaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_nl='Canadese dollar',cu_sub_name_nl='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_nl='Congolese frank',cu_sub_name_nl='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_nl='Zwitserse frank',cu_sub_name_nl='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_nl='Chileense peso',cu_sub_name_nl='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_nl='Chinese Yuan',cu_sub_name_nl='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_nl='Colombiaanse peso',cu_sub_name_nl='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_nl='Colombiaanse unidad de valor real',cu_sub_name_nl='' WHERE cu_iso_3='COU';
UPDATE static_currencies SET cu_name_nl='Costa Ricaanse colón',cu_sub_name_nl='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_nl='Servische dinar',cu_sub_name_nl='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_nl='Cubaanse peso',cu_sub_name_nl='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_nl='Kaapverdische escudo',cu_sub_name_nl='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_nl='Tsjechische kroon',cu_sub_name_nl='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_nl='Djiboutiaanse frank',cu_sub_name_nl='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_nl='Deense kroon',cu_sub_name_nl='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_nl='Dominicaanse peso',cu_sub_name_nl='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_nl='Algerijnse dinar',cu_sub_name_nl='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_nl='Estse kroon',cu_sub_name_nl='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_nl='Egyptisch pond',cu_sub_name_nl='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_nl='Eritrese nakfa',cu_sub_name_nl='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_nl='Ethiopische birr',cu_sub_name_nl='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_nl='Euro',cu_sub_name_nl='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_nl='Fiji-dollar',cu_sub_name_nl='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_nl='Falklandeilands pond',cu_sub_name_nl='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_nl='Britse Pound Sterling',cu_sub_name_nl='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_nl='Georgische lari',cu_sub_name_nl='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_nl='Ghanese cedi (Vervalt per 31 december 2007)',cu_sub_name_nl='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_nl='Ghanese cedi (Geldig per 1 juli 2007)',cu_sub_name_nl='' WHERE cu_iso_3='GHS';
UPDATE static_currencies SET cu_name_nl='Gibraltarees pond',cu_sub_name_nl='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_nl='Gambiaanse dalasi',cu_sub_name_nl='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_nl='Guineese frank',cu_sub_name_nl='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_nl='Guatemalaanse Quetzal',cu_sub_name_nl='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_nl='Guyaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_nl='Hongkongse dollar',cu_sub_name_nl='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_nl='Hondurese lempira',cu_sub_name_nl='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_nl='Kroatische kuna',cu_sub_name_nl='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_nl='Haïtiaanse gourde',cu_sub_name_nl='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_nl='Hongaarse forint',cu_sub_name_nl='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_nl='Indonesische roepia',cu_sub_name_nl='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_nl='Nieuwe Israëlische shekel',cu_sub_name_nl='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_nl='Indiase roepie',cu_sub_name_nl='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_nl='Iraakse dinar',cu_sub_name_nl='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_nl='Iraanse rial',cu_sub_name_nl='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_nl='IJslandse kroon',cu_sub_name_nl='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_nl='Jamaicaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_nl='Jordaanse dinar',cu_sub_name_nl='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_nl='Japanse yen',cu_sub_name_nl='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_nl='Keniaanse shilling',cu_sub_name_nl='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_nl='Kirgizische som',cu_sub_name_nl='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_nl='Cambodjaanse riel',cu_sub_name_nl='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_nl='Comorese frank',cu_sub_name_nl='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_nl='Noord-Koreaanse won',cu_sub_name_nl='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_nl='Zuid-Koreaanse won',cu_sub_name_nl='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_nl='Koeweitse dinar',cu_sub_name_nl='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_nl='Caymaneilandse dollar',cu_sub_name_nl='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_nl='Kazachstaanse tenge',cu_sub_name_nl='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_nl='Laotiaanse kip',cu_sub_name_nl='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_nl='Libanees pond',cu_sub_name_nl='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_nl='Srilankaanse roepie',cu_sub_name_nl='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_nl='Liberiaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_nl='Lesotho loti',cu_sub_name_nl='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_nl='Litouwse litas',cu_sub_name_nl='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_nl='Letse lats',cu_sub_name_nl='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_nl='Libische dinar',cu_sub_name_nl='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_nl='Marokkaanse dirham',cu_sub_name_nl='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_nl='Moldavische leu',cu_sub_name_nl='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_nl='Malagassische ariary',cu_sub_name_nl='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_nl='Macedonische denar',cu_sub_name_nl='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_nl='Myanmarese Kyat',cu_sub_name_nl='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_nl='Mongolisch Tugrik',cu_sub_name_nl='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_nl='Macause Pataca',cu_sub_name_nl='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_nl='Mauritanische Ouguiya',cu_sub_name_nl='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_nl='Maltese lira',cu_sub_name_nl='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_nl='Mauritiaanse roepie',cu_sub_name_nl='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_nl='Maldivische rufiyaa',cu_sub_name_nl='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_nl='Malawische kwacha',cu_sub_name_nl='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_nl='Mexicaanse peso',cu_sub_name_nl='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_nl='Maleisische ringgit',cu_sub_name_nl='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_nl='Mozambicaanse metical',cu_sub_name_nl='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_nl='Namibische dollar',cu_sub_name_nl='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_nl='Nigeriaanse Naira',cu_sub_name_nl='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_nl='Nicaraguaanse Córdoba Oro',cu_sub_name_nl='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_nl='Noorse kroon',cu_sub_name_nl='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_nl='Nepalese roepie',cu_sub_name_nl='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_nl='Nieuw-Zeelandse dollar',cu_sub_name_nl='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_nl='Omaanse rial',cu_sub_name_nl='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_nl='Panamese balboa',cu_sub_name_nl='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_nl='Nieuwe Peruviaanse sol',cu_sub_name_nl='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_nl='Papoease kina',cu_sub_name_nl='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_nl='Filipijnse peso',cu_sub_name_nl='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_nl='Pakistaanse roepie',cu_sub_name_nl='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_nl='Poolse zloty',cu_sub_name_nl='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_nl='Paraguayaanse guaraní',cu_sub_name_nl='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_nl='Qatarese rial',cu_sub_name_nl='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_nl='Roemeense leu',cu_sub_name_nl='' WHERE cu_iso_3='RON';
UPDATE static_currencies SET cu_name_nl='Russische roebel',cu_sub_name_nl='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_nl='Rwandese frank',cu_sub_name_nl='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_nl='Saoedi-Arabische riyal',cu_sub_name_nl='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_nl='Salomon-dollar',cu_sub_name_nl='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_nl='Seychelse roepie',cu_sub_name_nl='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_nl='Soedanese pond',cu_sub_name_nl='' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_nl='Zweedse kroon',cu_sub_name_nl='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_nl='Singaporese dollar',cu_sub_name_nl='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_nl='Sint-Heleens pond',cu_sub_name_nl='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_nl='Slowaakse kroon',cu_sub_name_nl='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_nl='Sierraleoonse leone',cu_sub_name_nl='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_nl='Somalische shilling',cu_sub_name_nl='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_nl='Surinaamse dollar',cu_sub_name_nl='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_nl='Sao Tomeese dobra',cu_sub_name_nl='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_nl='Salvadoraanse colón',cu_sub_name_nl='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_nl='Syrisch pond',cu_sub_name_nl='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_nl='Swazilandse lilangeni',cu_sub_name_nl='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_nl='Thaise baht',cu_sub_name_nl='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_nl='Tadzjiekse somoni',cu_sub_name_nl='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_nl='Turkmeense manat',cu_sub_name_nl='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_nl='Tunesische dinar',cu_sub_name_nl='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_nl='Tonganese pa\'anga',cu_sub_name_nl='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_nl='Timorese escudo',cu_sub_name_nl='' WHERE cu_iso_3='TPE';
UPDATE static_currencies SET cu_name_nl='Nieuwe Turkse Lira',cu_sub_name_nl='' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_nl='Trinidad en Tobago dollar',cu_sub_name_nl='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_nl='Nieuwe Taiwanese dollar',cu_sub_name_nl='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_nl='Tanzaniaanse shilling',cu_sub_name_nl='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_nl='Oekraïense grivna',cu_sub_name_nl='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_nl='Oegandese shilling',cu_sub_name_nl='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_nl='Amerikaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_nl='Uruguayaanse peso',cu_sub_name_nl='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_nl='Oezbekistaanse sum',cu_sub_name_nl='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_nl='Venezolaanse bolívar',cu_sub_name_nl='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_nl='Vietnamese dong',cu_sub_name_nl='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_nl='Vanuatu vatu',cu_sub_name_nl='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_nl='Samoa tala',cu_sub_name_nl='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_nl='CFA-frank BEAC',cu_sub_name_nl='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_nl='Jemenitische rial',cu_sub_name_nl='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_nl='Zuid-Afrikaanse rand',cu_sub_name_nl='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_nl='Zambiaanse kwacha',cu_sub_name_nl='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_nl='Zimbabwaanse dollar',cu_sub_name_nl='' WHERE cu_iso_3='ZWD';
## static_languages
UPDATE static_languages SET lg_name_nl='Afar, Hamitisch' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Abchazisch' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Avestisch' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Afrikaans' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Akan' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Amhaars, Amharisch' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Aragonees' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Arabisch' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Assamees, Assami' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Avaars' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Aymara, Aymará' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Azeri, Azerbeidzjaans' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Basjkiers, Basjkirisch' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Wit-Russisch, Belarussisch' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bulgaars' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bihari' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bislama' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bambara' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bengaals' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tibetaans' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bretons' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Bosnisch' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Catalaans' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tsjetsjeens' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Chamorro' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Corsicaans' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Cree' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tsjechisch' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kerkslavisch' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tsjoevasjisch' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Welsh' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Deens' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Duits' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Divehi' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Dzongkha' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Ewe' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Grieks' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Engels' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Esperanto' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Spaans' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Estisch, Ests' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Baskisch' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Perzisch, Farsi' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Fula' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Fins' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Fijisch' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Faeröers' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Frans' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Fries' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Iers-Gaelisch' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Schots-Gaelisch' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Galicisch' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Guaraní' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Gujarati' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Manx-Gaelisch' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Hausa' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Hebreeuws' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Hindi' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Hiri Motu' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kroatisch' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kreyòl' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Hongaars' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Armeens' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Herero' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Interlingua' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Indonesisch' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Interlingue' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Igbo' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Yi' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Inupiak' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Ido' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='IJslands' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Italiaans' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Inuktitut' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Japans' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Javaans' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Georgisch' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kikongo' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Gikuyu' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kwanyama' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kazachs' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Groenlands' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Khmer, Cambodjaans' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kannada, Kanarees, Kanara' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Koreaans' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kanuri' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kasjmiri, Kasjmiers, Kasjmirs' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Koerdisch' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Zurjeens' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Cornisch' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kirgizisch' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Latijn' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Luxemburgs' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Luganda' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Limburgs' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Lingala' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Laotiaans' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Litouws' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Luba-Katanga' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Lets' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Plateaumalagasi' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Marshallees' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Maori' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Macedonisch' WHERE lg_iso_2='MK / SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Malayalam' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Mongools' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Moldavisch' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Marathi' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Maleis' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Maltees' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Birmaans, Birmees' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Nauruaans' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Norwegian Bokmål' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Noord-Ndebele' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Nepalees, Nepali' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Ndonga' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Nederlands' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Nynorsk' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Noors' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Zuid-Ndebele' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Navajo' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Nyanja' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Occitaans' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Ojibweg' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Afaan Oromo' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Oriya' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Ossetisch' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Punjabi' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Pali' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Pools' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Pasjtoe, Pasjto, Pashtoe' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Portugees' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Portugees' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_nl='Quechua' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Reto-Romaans' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kirundi' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Roemeens' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Russisch' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Kinyarwanda' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Sanskriet' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Sardijns' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Sindhi' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Noord-Samisch, Noord-Laps' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Sangho' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Servokroatisch' WHERE lg_iso_2='SH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Singalees' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Slowaaks, Slovaaks' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Sloveens' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Samoaans' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Shona' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Somalisch' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Albanees' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Servisch' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Swazi' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Zuid-Sotho' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Soendanees, Sundanees' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Zweeds' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Swahili' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tamil' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Telugu, Teloegoe' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tadzjieks' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Thai, Thais' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tigrinya' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Turkmeens, Toerkmeens' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tagalog' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tswana' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tongaans, Tonga' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Turks' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tsonga' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tataars, Tartaars' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Twi' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Tahitiaans' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Oeigoers, Oejgoers' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Oekraïens' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Urdu' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Oezbeeks' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Venda' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Vietnamees' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Volapük, Volapuk' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Waals' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Wolof' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Xhosa' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Jiddisch' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Yoruba' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Zhuang, Tsjoeang' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_nl='Chinees' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_nl='Chinees' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_nl='Zoeloe' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
## static_territories
UPDATE static_territories SET tr_name_nl='Afrika' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_nl='Oceanië' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_nl='Noord-, Midden- en Zuid-Amerika' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_nl='Azië' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_nl='Europa' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_nl='Oost-Azië' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_nl='Zuidoost-Azië' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_nl='Centraal-Azië' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_nl='West-Azië' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_nl='Zuid-Europa' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_nl='Oost-Europa' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_nl='Noord-Europa' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_nl='West-Europa' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_nl='Zuid-Amerika' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_nl='Midden-Amerika' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_nl='Noord-Amerika' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_nl='Caribiën' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_nl='West-Afrika' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_nl='Oost-Afrika' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_nl='Noord-Afrika' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_nl='Centraal-Afrika' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_nl='Zuid-Afrika' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_nl='Australië en Nieuw-Zeeland' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_nl='Melanesië' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_nl='Micronesië' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_nl='Polynesië' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_nl='Zuid-Azië' WHERE tr_iso_nr='34';